# Generated by Django 6.0.3 on 2026-06-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_task_owner'),
    ]

    operations = [
    ]
