# Generated by Django 6.0.3 on 2026-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_alter_leaverequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
    ]
